before_script:
        #  - python -V # Print out python version for debugging

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  CI_PROJECT_DIR: $CI_PROJECT_DIR
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - test
  - container
  - deploy

test_job:
  stage: test
  image: python:latest
  script:
    - echo "Running tests"
    - python -m unittest discover -s "./tests/"

deploy_container:
  stage: container
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker build -t $TAG_COMMIT -t $TAG_LATEST .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST

deploy_job:
  stage: deploy
  image: alpine:latest
  tags:
    - deployment
  script:
    - chmod og= $ID_RSA
    - apk add python3
    - apk update && apk add openssh-client
    - ssh -v -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull $TAG_COMMIT"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker container rm -f python-gitlab || true"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -p 80:80 -d $TAG_COMMIT"
  environment:
    name: production
    url: http://192.168.88.132
  only:
    - master

